package reqModel

import "lottery/welfare/model"

//彩票类型
type LotteryResp struct {
	Reason    string          `json:"reason"`
	Result    []model.Lottery `json:"result"`
	ErrorCode int             `json:"error_code"`
}

//兑奖记录
type Awarding struct {
	Reason    string         `json:"reason"`
	Awarding  model.Awarding `json:"result"`
	ErrorCode int            `json:"error_code"`
}

//开奖记录
type LotteryQuery struct {
	Reason           string                 `json:"reason"`
	LotteryOpenQuery model.LotteryOpenQuery `json:"result"`
	ErrorCode        int                    `json:"error_code"`
}

type AutoGeneratedMap struct {
	Status int    `json:"status"`
	Result Result `json:"result"`
}
type Location struct {
	Lng float64 `json:"lng"`
	Lat float64 `json:"lat"`
}

//map api返回
type Result struct {
	Location      Location `json:"location"`
	Precise       int      `json:"precise"`
	Confidence    int      `json:"confidence"`
	Comprehension int      `json:"comprehension"`
	Level         string   `json:"level"`
}
